class Range:
    """This class would supply len and __getitem__ methods to find the
    number of elements that are generated by the range function and to get the element
    at a particular index.
    """

    def __init__(self, start, stop=None, step=1) -> None:
        self._start = start
        self._stop = stop
        self._step = step
        self._length = max(0, (stop - start + step - 1) / step)

    def __len__(self) -> int:
        return self._length

    def __getitem__(self, index) -> int:
        if index < 0:
            # in python, you can use -ve indices to donate reverse traversing (back to front)
            index += len(self)
        if not 0 <= index < len(self) - 1:
            raise IndexError("index out of range")
        return self.start + index * self._step
